language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

notifications:
  email: false

install:
  - sudo apt install curl
  - sudo curl https://github.com/PhyloSofS-Team/ProGraphMSA/raw/master/bin/ProGraphMSA_64 --output /bin/ProGraphMSA
  - python -m pip install coveralls codecov
  - python -m pip install sphinx sphinx_rtd_theme sphinx-argparse
  - python -m pip install .

script:
  - export PYTEST_ADDOPTS="--pylint"
  - python setup.py test

after_success:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then coveralls; fi
  - export SPHINX_APIDOC_OPTIONS=members
  - sphinx-apidoc -o docs/source/api thoraxe
  - sphinx-build docs/source docs/build/html
  - ./push_docs.sh

env:
  global:
    - secure: "ImllK7Yskp7PKXz1YhXt7TzwZeDZoY4ph3L6hkXDxGCw9HJGghfSzRIj22XZlx1JJDi9KprZjroWmn15+yhGz17ufKhN5GH+LbOFefRB6PliJYBw6SmFxZeHp+TPxR2onY7FbqNlctcUW08z5Hw4SL7Oh4Z5QOz/cFrrcQZhjdibPFMb9XLAkBMn3HvVXbmp2arCywerdhugPu9q2LcWbAeRfLXqKwnJt4ZkC/k1A+pfC4zja5fgUv07BvMbASxmC7v3jRkvhfB+VS06RaTT/zpm3yYrKtFjgrJh0l/wV8YuGOYhL2peNi4GTPA7TXFF/+6i4CXmG2BEdI6P9oqPjpUPXp0nrqXgfCzmT46/uT1dSNO2iJnPlL7/9bB0xix/NMmnBeL1zx6ewMFNfyMkACrJj5KdosSscpAQmeeBoWkJDXzeBfp1kUvRK3OwcayLoTmBQ7UIKd7QUu9+jsAhAmVfQPemBj5XecbNvBJVDOTlQ+zWlKLlsKzqm6TgSIehr2gNIM/VSfUx+ntzDNuq57ISEGpMRrGMfFdDt9ZzkquM1Yiz1nSLdqsNB4nd24z6lFpif0Zl7PY7JHAxiEOFqCSYw8C4WbndD0pbfhJtcBD14fvtwnpw5hZoKNidKN5B2COaGuFSuiy9NmxHAkQmWf7BajmnHIYkutM08HcPsNk="
